spring.application.name=resumeanalyzer
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/resume_analyzer
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# File Upload Configuration
app.upload.dir=uploads/resumes

# JWT Configuration
app.jwtSecret=${JWT_SECRET:mySecretKeyForJWTTokenGenerationAndValidationPurpose12345678901234567890}
app.jwtExpirationInMs=86400000

